version: '3.8'

services:
  applio-tts:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./cache:/app/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  load-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      applio-tts:
        condition: service_healthy
    volumes:
      - ./scripts:/app/scripts
    command: ["python", "/app/scripts/load_test.py", "http://applio-tts:8000", "--users", "50", "--duration", "300"]
